import pandas as pd
df = pd.read_json(r'C:\Users\egoncal9\PycharmProjects\pythonProject2\ethos_test\newversion2.json')
teste = df.iloc[:,0].dropna(axis=0)

# Removing breaklines
new_serie = teste.replace(r'\n',r'',regex=True)

lista = [r'\n\n          \n            \n              \n\n              \n\n              \n\n              \n\n              \n                ',r'\n                   ',r'\n                ',r'\n              \n\n              \n            \n            \n              \n                ',r'\n                  ',r'\n                ',r'\n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n                  \n\n                  ',r'\n                      ',r'Perfil de CEO: como é o líder do futuro?',r'\n                  ',r'\n\n                  \n\n                  \n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              ',r'\n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n            \n              \n\n              \n\n              \n\n              \n\n              \n\n              \n            \n\n            ',r'\n                \n                ',r'\n                    \n                    \n                ',r'\n            ',r'\n\n            ',r'\n\n          \n\n        ']

for element in lista:
    print(new_serie.replace(element,'', regex=True))